### ISSUE TITLE
I'm confused. I have Emerald EX Speedchoice, but it's not randomized? How do I change that?

### ISSUE THREAD

**Issue by Zadowcloud** [ProjectRevoTPP/pokeemerald-ex-speedchoice#13]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version of EX**
[e.g. 0.2.6]

**If applicable, what was version of EX was it known to work on?:**
[e.g. 0.2.4]

**Additional context**

**Comment by ProjectRevoTPP** [comment]
Please read the releases ffs
