### ISSUE TITLE
Saving Randomizer doesnt work with newest Java Version

### ISSUE THREAD

**Issue by DeadAiim** [ProjectRevoTPP/pokeemerald-ex-speedchoice#14]
**Describe the bug**
Tried running Randomizer with Java 1.6 and with newest Version 8 Update 341. Since i tried the latest Java which is described in the Randomizer and the newest Version i cant use the Randomizer, which is quite sad since i was very happy to find such Randomizer/Mod.

**To Reproduce**
Try to safe Randomizer, or load Settings

**Expected behavior**
Nothing happens, cant safe, load or anything. But Saving Settings will work into RNQS

**Screenshots**
-

**Version of EX**
[e.g. 0.9.3]

**If applicable, what was version of EX was it known to work on?:**
pokeemerald-ex-speedchoice-0.3.0.x delta

**Additional context**
UPR-Speedchoice v2.0.0-alpha (2021-05-01)

**Comment by mateon1** [comment]
Java 8 is very old. The most recent version of Java right now is Java **18**. The reason Java 8 is still being updated is to help with old broken software that can't run on newer Java versions, but Java 8 is missing a ton of new features.

**Comment by DeadAiim** [comment]
Im ashamed to say it worked with Java 18. Thank your very much for helping me out!
