### ISSUE TITLE
Double battles: fainted opponents are affected by abilities

### ISSUE THREAD

**Issue by choatix** [ProjectRevoTPP/pokeemerald-ex-speedchoice#4]
**Describe the bug**
When in a double battle, and an ability activates such as Cotton Down or Frisk, fainted opponents will also be affected. I have only noticed the issue regarding the two listed abilities.

**To Reproduce**
1) Obtain a pokemon with Cotton Down (Debug menu possible, or reading randomiser log)
2) Enter a double battle (earliest would be just before Roxanne)
3) Knock out one of the opponents on their side
4) Knock out or be attacked on the pokemon with Cotton Down
5) Cotton Down will activate, including on the fainted mon

**Expected behavior**
Only pokemon that have have not fainted should be affected by abilities.

**Screenshots**
![image](https://user-images.githubusercontent.com/6518223/125319881-14660680-e333-11eb-96a8-342814a8b196.png)

**Version of EX**
Originally found on 0.2.4. Replicated on 0.2.6.

**If applicable, what was version of EX was it known to work on?:**
N/A

**Additional context**

**Comment by ProjectRevoTPP** [comment]
There is now a policy of one issue per move/ability; since Cotton Down is already fixed I will leave this one open but any further issues must be split up.

**Comment by ProjectRevoTPP** [comment]
Please show screens of Frisk doing this.

**Comment by choatix** [comment]
If there is a release in-coming, I will try to replicate again, as current version debug menu for ability does not update so very difficult to set up the conditions, and I presume this would already be fixed in upcoming release. If not known, let me know and I will create another ticket for the debug menu issue with setting abilities.

**Comment by ProjectRevoTPP** [comment]
Then can you describe the conditions needed?

**Comment by ProjectRevoTPP** [comment]
Closing due to lack of info.
