### ISSUE TITLE
Various moves do not have their effects correctly done

### ISSUE THREAD

**Issue by pokemonfan1937** [ProjectRevoTPP/pokeemerald-ex-speedchoice#5]
**Describe the bug**
Beak Blast fails when being hit by the opponent. 
Shell Trap can softlock the game when used. No matter what kind of move the opponent uses(Physical, Special, Status), this softlock always occurs unless the user is KO'd after being hit.
Clanging Scales does not reduce the user's Defense.
Scale Shot does not increase the user's Speed and lower the user's Defense.

**To Reproduce**
1. Get a Pokemon with these moves(Debug menu is most convenient way)
2. Fight a Trainer(preferably with a wide variety of moves)
3. Use the moves and see

**Expected behavior**
Beak Blast: Should fire off even when hit
Shell Trap: Shouldn't be able to softlock the game
Clanging Scales: Should lower the user's Defense when used
Scale Shot: Should lower the user's Defense and raise the user's Speed when used

**Screenshots**
https://youtu.be/C66tl46NZ-M

**Version of EX**
0.2.6

**If applicable, what was version of EX was it known to work on?:**
N/A

**Comment by ProjectRevoTPP** [comment]
One issue per move/effect please. I am closing this.
