### ISSUE TITLE
Pokeball Priority

### ISSUE THREAD

**Issue by choatix** [ProjectRevoTPP/pokeemerald-ex-speedchoice#8]
**Describe the bug**
The order of operations is incorrect when throwing pokeballs.

**To Reproduce**
1. Be slower than the opponent.
2. Throw a pokeball

**Expected behavior**
You would expect the poke-ball to have a higher priority than the opponent attacking.

**Screenshots/AVI File**
https://user-images.githubusercontent.com/6518223/125978403-d141fafa-588a-4797-a388-c58f617ecfc4.mov

**Version of EX**
0.2.6

**If applicable, what was version of EX was it known to work on?:**
N/A

**Comment by ProjectRevoTPP** [comment]
This is already fixed locally, not committed yet.
