### ISSUE TITLE
Nerf first rival

### ISSUE THREAD

**Issue by easyaspi314** [ProjectRevoTPP/pokeemerald-ex-speedchoice#9]
**Is your feature request related to a problem? Please describe.**
The Route 103 rival battle has super effective STAB against your starter due to the modified learnsets, making the battle very one-sided without some grinding.

**Describe the solution you'd like**
Remove the STAB moves so they only have Tackle/Growl (Mudkip), Scratch/Growl (Torchic) or Pound/Leer (Treecko).

**Comment by ProjectRevoTPP** [comment]
not fixing
